alert('Hello,Ryouhei');
alert(1+1);
alert(Math.sqrt(1+1));
・２の平方根と3の平方根の和を計算しなさい。
・1を0でわるとどうなるか、試してみなさい。
・0を0で割るとどうなるか、試してみなさい。
alert(2+3);
alert('2'+'3');
alert(Number('2')+Number('3'));
alert('2'+3);
